export const products = [
  {
    id: 1,
    title: "Brazalete 1",
    price: 15000,
    stock: 2,
    description: "Brazalete con diseño de mariposa en tonos vino y dorado.",
    category: "brazaletes",
    img: "https://res.cloudinary.com/dkrenmz5w/image/upload/v1682437286/brazalete1_nkmfr6.jpg",
  },
  {
    id: 2,
    title: "Broche 1",
    price: 10000,
    stock: 2,
    description: "Broche de nube arcoíris con incrustaciones brillantes.",
    category: "broches",
    img: "https://res.cloudinary.com/dkrenmz5w/image/upload/v1682437313/broche1_lzzxeu.jpg",
  },
  {
    id: 3,
    title: "Collar 1",
    price: 20000,
    stock: 2,
    description: "Collar con diseño de corazón e incrustaciones doradas.",
    category: "collares",
    img: "https://res.cloudinary.com/dkrenmz5w/image/upload/v1682437327/collar1_of0a0v.jpg",
  },
  {
    id: 4,
    title: "Zarcillos 1",
    price: 5000,
    stock: 2,
    description: "Zarcillos con diseño romboide en tonos dorados y negros.",
    category: "zarcillos",
    img: "https://res.cloudinary.com/dkrenmz5w/image/upload/v1682437340/zarcillos1_jvxat5.jpg",
  },
  {
    id: 5,
    title: "Brazalete 2",
    price: 18000,
    stock: 5,
    description: "Brazalete con patrones lineales en todos dorados y negros.",
    category: "brazaletes",
    img: "https://res.cloudinary.com/dkrenmz5w/image/upload/v1682437298/brazalete2_ngrvdx.jpg",
  },
  {
    id: 6,
    title: "Broche 2",
    price: 13000,
    stock: 2,
    description: "Broche de flor de Loto en todos pasteles y dorados.",
    category: "broches",
    img: "https://res.cloudinary.com/dkrenmz5w/image/upload/v1682437320/broche2_gsftxp.webp",
  },
  {
    id: 7,
    title: "Collar 2",
    price: 23000,
    stock: 2,
    description:
      "Collar con diseño de Mano de Hamsa en tonos agua, azul y rosa.",
    category: "collares",
    img: "https://res.cloudinary.com/dkrenmz5w/image/upload/v1682437334/collar2_abtl39.jpg",
  },
  {
    id: 8,
    title: "Zarcillos 2",
    price: 8000,
    stock: 2,
    description:
      "Zarcillos con diseño de banderín en tonos caoba, rojo y blanco.",
    category: "zarcillos",
    img: "https://res.cloudinary.com/dkrenmz5w/image/upload/v1682437347/zarcillos2_ajon5m.jpg",
  },
  //CREAR ARREGLO DE PRODUCTOS
];
